### ISSUE TITLE
It seems that the downloading link of trained_yolov4_modle is expired. How can i get a new one?

### ISSUE THREAD

**Issue by HengZhu96** [yamiyukiharu/trafficVehicleCounter#1]
Please.

**Comment by yamiyukiharu** [comment]
sorry man got no clue, maybe u can swap out the yolov4 model with something newer, the interface should not be too different i think

**Comment by HengZhu96** [comment]
> 

  I downloaded a new pre_trained model from https://github.com/AlexeyAB/darknet/releases/tag/yolov4 and then put in /trafficVehicleCounter-master/checkpoints/yolov4_416/. But the program seems not to process anything(I wait several hours for a one-minute video). Which step did I do wrong？Please.
